# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  update-properties:
    default: false
    type: boolean    

jobs:
    package-docker-utils:
    	docker:
          - image: maven:3.8.4-openjdk-17
    	working_directory: /docker-utils
    	steps:
          - checkout

          - run:
              name: Clean and Package Docker-Utils
              command: |
                mvn -s .circleci/settings.xml -f docker-utils/pom.xml clean package -Dspring.profiles.active=default

    package-object-utils:
        docker:
          - image: maven:3.8.4-openjdk-17  
     	working_directory: /object-utils
    	steps:
          - checkout
          
          - run:
              name: Clean and Package Object-Utils
              command: |
                mvn -s .circleci/settings.xml -f object-utils/pom.xml clean package -Dspring.profiles.active=default

    package-json-utils:
        docker:
          - image: maven:3.8.4-openjdk-17  
     	working_directory: /json-utils
    	steps:
          - checkout
          
          - run:
              name: Clean and Package Json-Utils
              command: |
                mvn -s .circleci/settings.xml -f json-utils/pom.xml clean package -Dspring.profiles.active=default

    package-class-utils:
        docker:
          - image: maven:3.8.4-openjdk-17  
     	working_directory: /class-utils
    	steps:
          - checkout
          
          - run:
              name: Clean and Package Class-Utils
              command: |
                mvn -s .circleci/settings.xml -f class-utils/pom.xml clean package -Dspring.profiles.active=default

workflows:
  version: 2
  package:
    when:
      not: << pipeline.parameters.update-properties >>
    jobs:
      - package-docker-utils
      - package-object-utils
      - package-json-utils
      - package-class-utils
